services:
  - type: web
    name: webwithpostgresql
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/WebwithPostgresql-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d2502b2dbo4c73a60ebg-a:5432/studentdb_2njf
      - key: SPRING_DATASOURCE_USERNAME
        value: studentdb_2njf_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: VFaa5dRQmWqQQt6I3yPMKK6xHBLXEvlU
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
